apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  secretname: istio-ingressgateway-certs
  issuerRef:
    name: letsencrypt-prod
  commonName: "*.iowa.weavedx.com"
  dnsNames:
  - iowa.weavedx.com
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - "*.iowa.weavedx.com"
      - "iowa.weavedx.com"
