# Istio defaults for Iowa GKE cluster (region us-central1 zone us-central1-a)
global:
  nodePort: false
  proxy:
    # replace with your GKE IP ranges
    includeIPRanges: "10.4.0.0/14,10.0.0.0/20"

sidecarInjectorWebhook:
  enabled: true
  enableNamespacesByDefault: false

gateways:
  enabled: true
  istio-ingressgateway:
    replicaCount: 2
    autoscaleMin: 2
    autoscaleMax: 2
    # replace with your Istio Gateway IP
    loadBalancerIP: "35.193.191.33"
    type: LoadBalancer

mixer:
  enabled: true
  replicaCount: 2
  autoscaleMin: 2
  autoscaleMax: 2

  istio-policy:
    autoscaleEnabled: true
    autoscaleMin: 2
    autoscaleMax: 2

  istio-telemetry:
    autoscaleEnabled: true
    autoscaleMin: 2
    autoscaleMax: 2

pilot:
  enabled: true
  replicaCount: 1
  autoscaleMin: 1
  autoscaleMax: 1
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi

grafana:
  enabled: true
  security:
    enabled: false
    secretName: grafana
    usernameKey: admin
    # change the password
    passphraseKey: admin

prometheus:
  enabled: true

servicegraph:
  enabled: true

tracing:
  enabled: true

certmanager:
  enabled: true
