# Istio defaults for Iowa GKE cluster (region us-central1 zone us-central1-a)
global:
  nodePort: false
  proxy:
    # replace with your GKE IP ranges
    includeIPRanges: "10.4.0.0/14,10.0.0.0/20"

sidecarInjectorWebhook:
  enabled: true
  enableNamespacesByDefault: false

gateways:
  enabled: true
  istio-ingressgateway:
    replicaCount: 2
    autoscaleMin: 2
    autoscaleMax: 3
    # replace with your Istio Gateway IP
    loadBalancerIP: "35.193.191.33"
    type: LoadBalancer

grafana:
  enabled: true
  security:
    enabled: false
    secretName: grafana
    usernameKey: admin
    # change the password
    passphraseKey: admin

prometheus:
  enabled: true

servicegraph:
  enabled: true

tracing:
  enabled: true

certmanager:
  enabled: true
