---
apiVersion: flux.weave.works/v1beta1
kind: FluxHelmRelease
metadata:
  name: flagger
  namespace: istio-system
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~0.0.1
spec:
  releaseName: flagger
  chart:
    repository: https://stefanprodan.github.io/flagger/
    name: flagger
    version: 0.0.1
  values:
    image:
      repository: stefanprodan/flagger
      tag: 0.0.1
      pullPolicy: IfNotPresent
    controlLoopInterval: "15s"
    metricsServer: "http://prometheus.istio-system.svc.cluster.local:9090"
    crd:
      create: true
    rbac:
      create: true
