---
apiVersion: flux.weave.works/v1beta1
kind: FluxHelmRelease
metadata:
  name: flagger-grafana
  namespace: istio-system
  annotations:
    flux.weave.works/ignore: "true"
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~0.1
spec:
  releaseName: flagger-grafana
  chart:
    repository: https://flagger.io
    name: grafana
    version: 0.1.0
  values:
    url: "http://prometheus.istio-system.svc.cluster.local:9090"
